### ISSUE TITLE
NameError: name '_git_commands' is not defined

### ISSUE THREAD

**Issue by gmkado** [sirbabyface/TortoiseGit4Fman#1]
I'm using the following versions:
fman 1.6.0 
TortoiseGit 2.8.0.0
git version 2.20.1.windows.1

I got the following error when trying to run ListGitCommands:

> Command 'ListGitCommands' raised error.
> 
> Traceback (most recent call last):
>   File "fman\impl\plugins\command_registry.py", line 128, in \_execute\_command
>   File "C:\Users\gkado\AppData\Roaming\fman\Plugins\Third-party\TortoiseGit4Fman\tortoise_git\\\_\_init\_\_.py", line 34, in \_\_call\_\_
>     result = show_quicksearch(self.\_get\_items)
>   File "fman\_\_init\_\_.py", line 235, in show_quicksearch
>   File "fman\impl\util\qt\thread.py", line 11, in result
>   File "fman\impl\util\qt\thread.py", line 81, in run_in_thread
>   File "fman\impl\util\qt\thread.py", line 106, in result
>   File "fman\impl\util\qt\thread.py", line 94, in \_\_call\_\_
>   File "fman\impl\widgets.py", line 368, in show_quicksearch
>   File "fman\impl\util\qt\thread.py", line 11, in result
>   File "fman\impl\util\qt\thread.py", line 66, in run_in_thread
>   File "fman\impl\widgets.py", line 383, in exec_dialog
>   File "fman\impl\quicksearch.py", line 35, in exec
>   File "fman\impl\quicksearch.py", line 108, in \_update\_items
>   File "C:\Users\gkado\AppData\Roaming\fman\Plugins\Third-party\TortoiseGit4Fman\tortoise_git\\\_\_init\_\_.py", line 50, in \_get\_items
>     return \_git\_commands
> NameError: name '\_git\_commands' is not defined

**Comment by sirbabyface** [comment]
Fixed in release 1.3.0
